- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/AuthService.dart
- lib/Database/driver_provider.dart
- lib/Map/google_map.dart
- lib/NavigationPages/activity_page.dart
- lib/NavigationPages/home_page.dart
- lib/NavigationPages/profile_page.dart
- lib/login.dart
- lib/main.dart
- test/tester_files/new_home_page.dart
updated the polyline generation that starts within the user's current location and updates every 10 seconds. also improved the authservice
> Updated Polyline Generation

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/AuthService.dart
- lib/Database/driver_provider.dart
- lib/Database/map_provider.dart
- lib/Map/google_map.dart
- lib/NavigationPages/profile_page.dart
- lib/login.dart
- lib/main.dart
- test/tester_files/old_profile_design.dart
major UI update for ProfilePage and minor UI update for LogIn page
> Updated UI

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/map_provider.dart
- lib/Map/google_map.dart
when user moved 20 meters since the last polyline change, the polyline will regenerate instead of every 10 seconds.
> improve polyline generation

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/driver_provider.dart
- lib/Database/global.dart
- lib/Database/map_provider.dart
- lib/Database/passenger_capacity.dart
- lib/Database/passenger_provider.dart
- lib/Map/google_map.dart
- lib/Map/polylines_sample.dart
- lib/NavigationPages/home_page.dart
- lib/NavigationPages/main_page.dart
- lib/login.dart
- lib/main.dart
added passenger provider for fetching passengers(still incomplete) and also fixes error on updating last online in DB
> added passenger provider and minor bug fixes

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/passenger_provider.dart
- lib/NavigationPages/activity_page.dart
- lib/NavigationPages/main_page.dart
- lib/login.dart
- lib/main.dart
this method is still on initial phase, but it can now get the passenger booking that matches the driver's id and based on the critical details like ride_status
> getBookingIDs is now working

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/passenger_provider.dart
- lib/NavigationPages/activity_page.dart
- lib/NavigationPages/main_page.dart
- lib/UI/constants.dart
Added Constants in the UI folder UI sizing and other constants
as of now, it has:
screenHeight
screenWidth
CORNER_RADIUS
CONTAINER_HEIGHT
BOX_SHADOW
GREEN_COLOR
WHITE_COLOR
> added a Constants file

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/map_provider.dart
- lib/Database/passenger_provider.dart
- lib/NavigationPages/activity_page.dart
- lib/NavigationPages/main_page.dart
- lib/login.dart
- lib/main.dart
minor fixes on code, added a dropoff location in map_provider
> minor fixes, removed passenger_counter page

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/map_provider.dart
- lib/Database/passenger_provider.dart
- lib/Map/google_map.dart
after identifying the nearest passenger, set the pick up location in map provider
> driver can now identify who is the nearest passenger

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/driver_provider.dart
- lib/Database/passenger_capacity.dart
- lib/NavigationPages/home_page.dart
- lib/NavigationPages/main_page.dart
- lib/login.dart
- lib/main.dart
passenger capacity will now based on how many passenger ride status is in ongoing ride status in the driver's vehicle
> new method to get passenger capacity

- lib/Database/global.dart
- lib/Database/passenger_capacity.dart
- lib/Database/passenger_provider.dart
> cleared some warnings

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/passenger_capacity.dart
- lib/Database/passenger_provider.dart
- lib/main.dart
the update is based on how many passengers are in ongoing trip in bookings table based on driverID
> added a function to update passenger capacity in vehicle table

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/driver_provider.dart
- lib/Database/map_provider.dart
- lib/Database/passenger_capacity.dart
- lib/Database/passenger_provider.dart
- lib/Map/google_map.dart
- lib/main.dart
> minor fixes on passenger capacity and nearest passenger pickup

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/passenger_provider.dart
- lib/NavigationPages/home_page.dart
- lib/main.dart
added a method to check all pickup locations and check those locations if they are in front of the driver and more than 20 meter ahead of the driver. accept booking if they are ahead of the driver, else mark as cancelled
> added a method to check if the booking distance

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/passenger_provider.dart
fixes the method for checking the distance between driver and passenger pick up location
> method fixing

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/map_provider.dart
- lib/Database/passenger_provider.dart
- lib/Map/google_map.dart
improve methods in getting all location of pickups in bookings and saving all valid bookings
> improvements on getting passenger bookings

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/driver_provider.dart
- lib/Database/passenger_capacity.dart
- lib/NavigationPages/home_page.dart
added a method to show the sitting and standing capacity in the home page UI of driver
> added sitting and standing capacity

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/driver_provider.dart
- lib/Database/map_provider.dart
- lib/Database/passenger_provider.dart
- lib/Map/google_map.dart
- lib/NavigationPages/activity_page.dart
- lib/NavigationPages/home_page.dart
- lib/NavigationPages/profile_page.dart
- lib/login.dart
moved the dependency of route coordinates from driver_routes_table to official_route table in the database and added some info tables in the activity page including completed, ongoing, requested bookings
> rebase the route coordinates to official_route

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/map_provider.dart
- lib/Database/passenger_capacity.dart
- lib/Database/passenger_provider.dart
- lib/Map/google_map.dart
- lib/NavigationPages/activity_page.dart
- lib/NavigationPages/profile_page.dart
- lib/main.dart
the passenger provider is more structured and readable compared to the last version... more maintainable and modifiable.
> major code improvements on passenger provider

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/driver_provider.dart
- lib/Map/google_map.dart
- lib/NavigationPages/activity_page.dart
- lib/NavigationPages/profile_page.dart
- added plate number data on profile page
- fixed ui in activity page
- added buildings enables in map
- adjust zoom to make the buildings render in map
> UI updates

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/passenger_provider.dart
- lib/NavigationPages/activity_page.dart
- if passenger pick up is ahead of the driver by 20 meters, considered as valid, mark as accepted.
- if passenger pick up is behind, considered as invalid, marked as cancelled in booking.
> updates the booking request based on the validity of booking

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/auth_service.dart
- lib/Database/driver_provider.dart
- lib/Database/map_provider.dart
- lib/Database/passenger_provider.dart
- lib/Map/google_map.dart
- lib/NavigationPages/profile_page.dart
- lib/main.dart
- fixed error on polyline not generating - results to a different numbers in intermediate points
- added a method to check how many intermediate points are in the route in officialRouteTable
- major code improvements and some rout response caching in the map provider
- improvements on booking processes
- added error handling in the app startup
- fixed some errors in map pins where pick up locations are not displaying
> Major changes on map and performance improvements

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/driver_provider.dart
- lib/Database/map_provider.dart
- lib/Map/google_map.dart
- lib/main.dart
- fixes the part where polyline generated is inverted/flipped
- improved overall implementation in map_provider and google_map
- VIBECODED
> Major code improvements

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Map/google_map.dart
- lib/NavigationPages/home_page.dart
- lib/NavigationPages/profile_page.dart
- added proximity check in passenger pick up and drop off location
- added button for picking up passenger, when clicked, the passenger booking will be marked as ongoing
- added button for dropping off passenger, when clicked, the passenger booking will be marked as completed
> Ride hailing progress: added proximity check, buttons for accepting and completing ride

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Config/app_config.dart
- lib/Database/passenger_provider.dart
- lib/Map/google_map.dart
- lib/NavigationPages/home_page.dart
- lib/NavigationPages/main_page.dart
- lib/README.md
- lib/UI/text_styles.dart
- pubspec.lock
- pubspec.yaml
- completed booking process for driver
- allows driver to only click confirm pick up and complete booking for easier operation and management of booking
- fixed errors encountered on the sequence of clicking confirm pickup and complete booking
- added important function for driver status which can only hail passenger when driver is in driving status
- also more code improvements for smoother app processes
> ride hailing complete

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Config/app_config.dart
- lib/Database/driver_provider.dart
- makes the driving status to lowercase in the database
- also adjust timings in fetching bookings
> minor tweaks in driver status

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Database/passenger_capacity.dart
- lib/Database/passenger_provider.dart
- lib/NavigationPages/home_page.dart
- lib/NavigationPages/main_page.dart
- lib/NavigationPages/profile_page.dart
- remodel the showstartdrivingdialog to a switch button
- switch  button cannot go to online status if the driver still has a passenger
> Logic fixes: fixed the logical error where driver can fetch booking even if the driver is not in the driving mode 

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- android/app/.cxx/RelWithDebInfo/1006el4v/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/RelWithDebInfo/1006el4v/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/RelWithDebInfo/1006el4v/x86/configure_fingerprint.bin
- android/app/.cxx/RelWithDebInfo/1006el4v/x86_64/configure_fingerprint.bin
- lib/Database/PASSENGER_CAPACITY_IMPROVEMENTS.md
- lib/Database/README.md
- lib/Database/booking_constants.dart
- lib/Database/booking_exception.dart
- lib/Database/booking_filter_service.dart
- lib/Database/booking_logger.dart
- lib/Database/booking_model.dart
- lib/Database/booking_repository.dart
- lib/Database/booking_repository_interface.dart
- lib/Database/location_service.dart
- lib/Database/passenger_capacity.dart
- lib/Database/passenger_provider.dart
- lib/Database/result.dart
- lib/NavigationPages/README.md
- lib/NavigationPages/activity_page.dart
- lib/NavigationPages/home_page.dart
- lib/NavigationPages/main_page.dart
- cleans the code and fixes some errors encountered
- fixes the error found in the passenger capacity
- separates the classes into files instead of combining multiple classes into one single file
- much more better
> Major code clean up

- README.md
- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/Config/app_config.dart
- lib/Map/google_map.dart
- lib/Map/save_location_db.dart
- lib/NavigationPages/activity_page.dart
- lib/NavigationPages/home_page.dart
- lib/NavigationPages/main_page.dart
- lib/common/logging/booking_logger.dart
- lib/data/repositories/supabase_booking_repository.dart
- lib/domain/services/booking_filter_service.dart
- lib/domain/services/passenger_capacity.dart
- lib/presentation/pages/home/README.md
- lib/presentation/pages/home/models/README.md
- lib/presentation/pages/home/models/passenger_status.dart
- lib/presentation/pages/home/utils/README.md
- lib/presentation/pages/home/utils/home_constants.dart
- lib/presentation/pages/home/utils/snackbar_utils.dart
- lib/presentation/pages/home/widgets/README.md
- lib/presentation/pages/home/widgets/floating_capacity.dart
- lib/presentation/pages/home/widgets/floating_message_button.dart
- lib/presentation/pages/home/widgets/floating_status_switch.dart
- lib/presentation/pages/home/widgets/passenger_list_widget.dart
- lib/presentation/providers/map_provider.dart
- lib/presentation/providers/passenger/passenger_provider.dart
separated business logics in the homepage and moved it to proper folder destination for an easy access and readable codebase
> Fixed home_page.dart and some code improvements

- android/app/.cxx/Debug/3vbp3066/arm64-v8a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/armeabi-v7a/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86/configure_fingerprint.bin
- android/app/.cxx/Debug/3vbp3066/x86_64/configure_fingerprint.bin
- lib/domain/services/passenger_capacity.dart
- lib/presentation/pages/home/controllers/home_controller.dart
- lib/presentation/pages/home/widgets/complete_ride_control.dart
- lib/presentation/pages/home/widgets/confirm_pickup_control.dart
- lib/presentation/providers/passenger/passenger_provider.dart
Introduced a new method for setting booking status, improved error handling, and added rollback functionality for capacity updates in ride completion and pickup confirmation. Enhanced reactivity in the home controller for booking changes.
> Refactor passenger capacity handling and booking status updates
